repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

      - id: markdownlint
        name: markdownlint
        description: "Checks the style of Markdown/Commonmark files."
        entry: markdownlint
        language: node
        types: [markdown]
        args: [--disable, line_length]

      - id: shellcheck
        name: shellcheck
        description: "Finds bugs in your shell scripts."
        entry: shellcheck
        language: system
        types: [shell]
